import React, { useState, useRef } from 'react';
import { Camera, Rocket, Globe, Star, Users, Calendar, DollarSign, Shield, ChevronRight, Sparkles, Moon, Sun, Mail, Phone, X, Check, Mountain, Waves, Cloud, Menu, MessageCircle, LogIn, UserPlus, LogOut, User, Send, Home, Package, MapPin } from 'lucide-react';

export default function AetheriaSpaceTravel() {
  const [selectedPackage, setSelectedPackage] = useState(null);
  const [isDarkMode, setIsDarkMode] = useState(true);
  const [formData, setFormData] = useState({ name: '', email: '', phone: '' });
  const [showBooking, setShowBooking] = useState(false);
  const [selectedWonder, setSelectedWonder] = useState(null);
  const [showSuccessModal, setShowSuccessModal] = useState(false);
  const [showSidebar, setShowSidebar] = useState(false);
  const [showAuthModal, setShowAuthModal] = useState(false);
  const [authMode, setAuthMode] = useState('login');
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [userInfo, setUserInfo] = useState(null);
  const [authForm, setAuthForm] = useState({ name: '', email: '', password: '' });
  const [showContactModal, setShowContactModal] = useState(false);
  const [contactForm, setContactForm] = useState({ name: '', email: '', message: '' });
  const [showFeedbackModal, setShowFeedbackModal] = useState(false);
  const [feedbackForm, setFeedbackForm] = useState({ rating: 5, message: '' });
  const [notification, setNotification] = useState({ show: false, message: '', type: 'success' });
  const [showProfileDropdown, setShowProfileDropdown] = useState(false);
  const [showEditProfile, setShowEditProfile] = useState(false);
  const [editForm, setEditForm] = useState({ name: '', email: '' });
  
  const packagesRef = useRef(null);
  const bookingRef = useRef(null);
  const featuresRef = useRef(null);
  const journeyRef = useRef(null);

  const showNotification = (message, type = 'success') => {
    setNotification({ show: true, message, type });
    setTimeout(() => {
      setNotification({ show: false, message: '', type: 'success' });
    }, 4000);
  };

  const scrollToSection = (ref) => {
    ref.current?.scrollIntoView({ behavior: 'smooth' });
    setShowSidebar(false);
  };

  const wonders = [
    { 
      id: 1,
      icon: Star, 
      title: "Crystal Caverns", 
      desc: "Explore caves filled with singing crystals that resonate with planetary energy", 
      color: "from-cyan-500 to-blue-500",
      fullDesc: "The Crystal Caverns of Aetheria are a geological marvel spanning over 500 kilometers underground. These mystical caves contain thousands of harmonic crystals that produce ethereal music when exposed to Aetheria's unique electromagnetic fields.",
      features: [
        "🎵 Singing Crystal Formations - Natural harmonics",
        "💎 Rare Aetherium Gems - Collect samples",
        "🌟 Bioluminescent Flora - Glowing cave plants",
        "🧘 Meditation Chambers - Experience tranquility",
        "📸 Professional Photography - Capture memories"
      ],
      duration: "4-6 hours",
      difficulty: "Easy to Moderate"
    },
    { 
      id: 2,
      icon: Cloud, 
      title: "Floating Islands", 
      desc: "Walk among sky islands suspended by natural magnetic fields", 
      color: "from-purple-500 to-pink-500",
      fullDesc: "Defying conventional physics, Aetheria's Floating Islands hover 2-5 kilometers above the surface, held aloft by powerful natural magnetic fields generated by the planet's unique iron-rich core. Home to rare sky-dwelling creatures and ancient ruins.",
      features: [
        "🏔️ Sky Bridges - Connect between islands",
        "🦅 Sky Fauna - Meet flying creatures",
        "🏛️ Ancient Temples - Explore ruins",
        "🎈 Zero-Gravity Zones - Experience weightlessness",
        "🌅 Sunset Observatory - Best views in galaxy"
      ],
      duration: "Full Day (8-10 hours)",
      difficulty: "Moderate"
    },
    { 
      id: 3,
      icon: Waves, 
      title: "Aurora Oceans", 
      desc: "Swim in waters that glow with ethereal bioluminescence", 
      color: "from-indigo-500 to-purple-500",
      fullDesc: "The Aurora Oceans contain trillions of bioluminescent microorganisms that create a mesmerizing light show 24/7. The water is perfectly safe, warm (25°C), and provides a once-in-a-lifetime swimming experience under purple skies.",
      features: [
        "🏊 Safe Swimming - Warm, gentle waters",
        "✨ Bioluminescent Plankton - Touch and glow",
        "🐚 Underwater Gardens - Coral-like formations",
        "🤿 Guided Diving - Professional instructors",
        "🌊 Aurora Surfing - Ride glowing waves"
      ],
      duration: "Half Day (4-5 hours)",
      difficulty: "Easy (Swimming skills helpful)"
    }
  ];

  const packages = [
    {
      id: 1,
      name: "Explorer Pass",
      price: "$299,999",
      duration: "7 Days",
      features: ["Surface Landing", "Crystal Caves Tour", "Northern Auroras View", "Standard Accommodation", "Daily Meals", "Safety Equipment"]
    },
    {
      id: 2,
      name: "Adventurer Elite",
      price: "$499,999",
      duration: "14 Days",
      features: ["Extended Surface Stay", "Floating Islands Tour", "Bioluminescent Ocean Dive", "Luxury Sky Pod", "Aetherian Cuisine", "Personal Guide", "All Activities Included"],
      popular: true
    },
    {
      id: 3,
      name: "Pioneer Ultimate",
      price: "$899,999",
      duration: "30 Days",
      features: ["Full Planet Exploration", "Private Spacecraft", "VIP Landing Sites", "Cultural Immersion", "Personal Guide", "Unlimited Activities", "Premium Souvenirs", "Priority Booking"]
    }
  ];

  const handleBooking = (pkg) => {
    if (!isLoggedIn) {
      showNotification('Please login or signup first to book a package! 🔐', 'error');
      setAuthMode('login');
      setShowAuthModal(true);
      return;
    }
    setSelectedPackage(pkg);
    setShowBooking(true);
    setTimeout(() => scrollToSection(bookingRef), 100);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    
    if (!isLoggedIn) {
      showNotification('Please login first! 🔐', 'error');
      setShowAuthModal(true);
      return;
    }

    setShowSuccessModal(true);
    setFormData({ name: '', email: '', phone: '' });
    setShowBooking(false);
    
    setTimeout(() => {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }, 100);
    
    setTimeout(() => {
      setShowSuccessModal(false);
    }, 8000);
  };

  const handleAuth = (e) => {
    e.preventDefault();
    
    if (authMode === 'signup') {
      if (!authForm.name || !authForm.email || !authForm.password) {
        showNotification('Please fill all fields! 📝', 'error');
        return;
      }
      setUserInfo({ name: authForm.name, email: authForm.email });
      setIsLoggedIn(true);
      showNotification(`Welcome to Aetheria Voyages, ${authForm.name}! 🎉`, 'success');
    } else {
      if (!authForm.email || !authForm.password) {
        showNotification('Please enter email and password! 📝', 'error');
        return;
      }
      setUserInfo({ name: authForm.email.split('@')[0], email: authForm.email });
      setIsLoggedIn(true);
      showNotification('Welcome back! 🎉', 'success');
    }
    
    setShowAuthModal(false);
    setAuthForm({ name: '', email: '', password: '' });
  };

  const handleLogout = () => {
    setIsLoggedIn(false);
    setUserInfo(null);
    setShowSidebar(false);
    setShowProfileDropdown(false);
    showNotification('Logged out successfully! 👋', 'success');
  };

  const handleEditProfile = () => {
    setEditForm({ name: userInfo.name, email: userInfo.email });
    setShowEditProfile(true);
    setShowProfileDropdown(false);
  };

  const handleSaveProfile = () => {
    if (!editForm.name || !editForm.email) {
      showNotification('Please fill all fields! 📝', 'error');
      return;
    }
    setUserInfo({ ...userInfo, name: editForm.name, email: editForm.email });
    setShowEditProfile(false);
    showNotification('Profile updated successfully! ✅', 'success');
  };

  const handleDeleteAccount = () => {
    if (window.confirm('Are you sure you want to delete your account? This action cannot be undone.')) {
      setIsLoggedIn(false);
      setUserInfo(null);
      setShowProfileDropdown(false);
      showNotification('Account deleted successfully! 🗑️', 'success');
    }
  };

  const handleContact = (e) => {
    e.preventDefault();
    if (!contactForm.name || !contactForm.email || !contactForm.message) {
      showNotification('Please fill all fields! 📝', 'error');
      return;
    }
    showNotification(`Thank you ${contactForm.name}! We'll get back to you soon! 📧`, 'success');
    setContactForm({ name: '', email: '', message: '' });
    setShowContactModal(false);
  };

  const handleFeedback = (e) => {
    e.preventDefault();
    if (!feedbackForm.message) {
      showNotification('Please write your feedback! 📝', 'error');
      return;
    }
    showNotification(`Thank you for your ${feedbackForm.rating} star feedback! ⭐`, 'success');
    setFeedbackForm({ rating: 5, message: '' });
    setShowFeedbackModal(false);
  };

  const bgClass = isDarkMode 
    ? "bg-gradient-to-br from-indigo-950 via-purple-900 to-slate-900" 
    : "bg-gradient-to-br from-blue-100 via-purple-100 to-pink-100";
  
  const textClass = isDarkMode ? "text-white" : "text-gray-900";
  const cardBg = isDarkMode ? "bg-white/10 backdrop-blur-lg" : "bg-white/80 backdrop-blur-lg";
  const accentColor = isDarkMode ? "text-cyan-400" : "text-purple-600";

  return (
    <div className={`min-h-screen ${bgClass} ${textClass}`}>
      {/* Custom Notification */}
      {notification.show && (
        <div className="fixed top-4 right-4 z-[110] animate-bounce">
          <div className={`${cardBg} border-2 ${
            notification.type === 'success' 
              ? (isDarkMode ? 'border-green-400' : 'border-green-500') 
              : (isDarkMode ? 'border-red-400' : 'border-red-500')
          } rounded-xl p-4 shadow-2xl max-w-sm`}>
            <div className="flex items-start gap-3">
              <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${
                notification.type === 'success' 
                  ? 'bg-gradient-to-br from-green-400 to-emerald-500' 
                  : 'bg-gradient-to-br from-red-400 to-red-600'
              }`}>
                {notification.type === 'success' ? (
                  <Check className="w-5 h-5 text-white" />
                ) : (
                  <X className="w-5 h-5 text-white" />
                )}
              </div>
              <p className="flex-1 font-semibold">{notification.message}</p>
              <button 
                onClick={() => setNotification({ show: false, message: '', type: 'success' })}
                className="hover:bg-white/10 rounded-full p-1"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Success Modal */}
      {showSuccessModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/70 backdrop-blur-md">
          <div className={`${cardBg} border-2 ${isDarkMode ? 'border-green-400' : 'border-green-500'} rounded-3xl p-8 max-w-md w-full text-center relative shadow-2xl`}
               style={{ animation: 'float 3s infinite' }}>
            <button 
              onClick={() => setShowSuccessModal(false)}
              className="absolute top-4 right-4 p-2 hover:bg-red-500/20 rounded-full transition-colors group"
            >
              <X className="w-6 h-6 group-hover:text-red-400 transition-colors" />
            </button>
            
            <div className="w-24 h-24 mx-auto mb-6 bg-gradient-to-br from-green-400 to-emerald-500 rounded-full flex items-center justify-center shadow-lg"
                 style={{ animation: 'pulse 2s infinite' }}>
              <Check className="w-14 h-14 text-white" strokeWidth={3} />
            </div>
            
            <h3 className="text-3xl sm:text-4xl font-bold mb-4 bg-gradient-to-r from-green-400 to-emerald-400 bg-clip-text text-transparent">
              Booking Confirmed! 🎉
            </h3>
            <p className="text-xl mb-3 font-semibold">Thank you {userInfo?.name}!</p>
            <p className="opacity-80 mb-6 leading-relaxed">
              Your journey to <span className="font-bold text-cyan-400">{selectedPackage?.name}</span> has been confirmed. 
              We'll send confirmation details to your email shortly.
            </p>
            
            <div className={`${isDarkMode ? 'bg-green-500/20 border border-green-400/30' : 'bg-green-100 border border-green-300'} rounded-xl p-5 mb-6`}>
              <p className="font-bold mb-3 text-lg flex items-center justify-center gap-2">
                <Rocket className="w-5 h-5" /> Next Steps:
              </p>
              <ul className="text-sm space-y-2 text-left">
                <li className="flex items-start gap-2">
                  <span className="text-green-400 font-bold">✓</span>
                  <span>Check your email for booking confirmation</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-green-400 font-bold">✓</span>
                  <span>Complete pre-flight medical assessment</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-green-400 font-bold">✓</span>
                  <span>Attend virtual orientation (3 days before launch)</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-green-400 font-bold">✓</span>
                  <span>Pack according to checklist we'll send</span>
                </li>
              </ul>
            </div>
            
            <button 
              onClick={() => setShowSuccessModal(false)}
              className={`w-full py-4 px-8 rounded-xl font-bold text-lg transition-all hover:scale-105 ${
                isDarkMode 
                  ? 'bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-400 hover:to-emerald-500' 
                  : 'bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-500 hover:to-emerald-500'
              } text-white shadow-lg`}
            >
              Awesome! Got It 🎊
            </button>
          </div>
        </div>
      )}

      {/* Auth Modal */}
      {showAuthModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/70 backdrop-blur-md">
          <div className={`${cardBg} border ${isDarkMode ? 'border-cyan-500/50' : 'border-purple-400'} rounded-3xl p-8 max-w-md w-full relative shadow-2xl`}>
            <button 
              onClick={() => setShowAuthModal(false)}
              className="absolute top-4 right-4 p-2 hover:bg-red-500/20 rounded-full transition-colors group"
            >
              <X className="w-6 h-6 group-hover:text-red-400" />
            </button>
            
            <div className="text-center mb-6">
              <div className={`w-16 h-16 mx-auto mb-4 rounded-full bg-gradient-to-br ${isDarkMode ? 'from-cyan-500 to-purple-600' : 'from-purple-500 to-pink-500'} flex items-center justify-center`}>
                {authMode === 'login' ? <LogIn className="w-8 h-8 text-white" /> : <UserPlus className="w-8 h-8 text-white" />}
              </div>
              <h3 className="text-2xl font-bold mb-2 bg-gradient-to-r from-cyan-300 to-purple-400 bg-clip-text text-transparent">
                {authMode === 'login' ? 'Welcome Back!' : 'Create Account'}
              </h3>
              <p className="opacity-75">{authMode === 'login' ? 'Login to book your journey' : 'Sign up to explore Aetheria'}</p>
            </div>

            <div className="space-y-4">
              {authMode === 'signup' && (
                <div>
                  <label className="block mb-2 font-semibold">Full Name</label>
                  <input
                    type="text"
                    value={authForm.name}
                    onChange={(e) => setAuthForm({...authForm, name: e.target.value})}
                    className={`w-full p-3 rounded-xl ${isDarkMode ? 'bg-white/10 border-cyan-500/30 text-white' : 'bg-white border-purple-300 text-gray-900'} border outline-none focus:border-cyan-400 transition-colors`}
                    placeholder="Enter your name"
                  />
                </div>
              )}
              
              <div>
                <label className="block mb-2 font-semibold">Email</label>
                <input
                  type="email"
                  value={authForm.email}
                  onChange={(e) => setAuthForm({...authForm, email: e.target.value})}
                  className={`w-full p-3 rounded-xl ${isDarkMode ? 'bg-white/10 border-cyan-500/30 text-white' : 'bg-white border-purple-300 text-gray-900'} border outline-none focus:border-cyan-400 transition-colors`}
                  placeholder="your@email.com"
                />
              </div>
              
              <div>
                <label className="block mb-2 font-semibold">Password</label>
                <input
                  type="password"
                  value={authForm.password}
                  onChange={(e) => setAuthForm({...authForm, password: e.target.value})}
                  className={`w-full p-3 rounded-xl ${isDarkMode ? 'bg-white/10 border-cyan-500/30 text-white' : 'bg-white border-purple-300 text-gray-900'} border outline-none focus:border-cyan-400 transition-colors`}
                  placeholder="Enter password"
                />
              </div>

              <button
                onClick={handleAuth}
                className={`w-full py-3 px-6 rounded-xl font-bold transition-all hover:scale-105 ${
                  isDarkMode 
                    ? 'bg-gradient-to-r from-cyan-500 to-purple-600 hover:from-cyan-400 hover:to-purple-500' 
                    : 'bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-400 hover:to-pink-400'
                } text-white shadow-lg`}
              >
                {authMode === 'login' ? 'Login' : 'Sign Up'} 🚀
              </button>

              <p className="text-center text-sm opacity-75">
                {authMode === 'login' ? "Don't have an account? " : "Already have an account? "}
                <button 
                  onClick={() => setAuthMode(authMode === 'login' ? 'signup' : 'login')}
                  className={`${accentColor} font-semibold hover:underline`}
                >
                  {authMode === 'login' ? 'Sign Up' : 'Login'}
                </button>
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Contact Modal */}
      {showContactModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/70 backdrop-blur-md">
          <div className={`${cardBg} border ${isDarkMode ? 'border-cyan-500/50' : 'border-purple-400'} rounded-3xl p-8 max-w-md w-full relative shadow-2xl`}>
            <button 
              onClick={() => setShowContactModal(false)}
              className="absolute top-4 right-4 p-2 hover:bg-red-500/20 rounded-full transition-colors group"
            >
              <X className="w-6 h-6 group-hover:text-red-400" />
            </button>
            
            <div className="text-center mb-6">
              <div className={`w-16 h-16 mx-auto mb-4 rounded-full bg-gradient-to-br from-cyan-500 to-blue-500 flex items-center justify-center`}>
                <Mail className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-2xl font-bold mb-2 bg-gradient-to-r from-cyan-300 to-purple-400 bg-clip-text text-transparent">
                Contact Us
              </h3>
              <p className="opacity-75">We'd love to hear from you!</p>
            </div>

            <div className="space-y-4">
              <div>
                <label className="block mb-2 font-semibold">Your Name</label>
                <input
                  type="text"
                  value={contactForm.name}
                  onChange={(e) => setContactForm({...contactForm, name: e.target.value})}
                  className={`w-full p-3 rounded-xl ${isDarkMode ? 'bg-white/10 border-cyan-500/30 text-white' : 'bg-white border-purple-300 text-gray-900'} border outline-none focus:border-cyan-400 transition-colors`}
                  placeholder="Enter your name"
                />
              </div>
              
              <div>
                <label className="block mb-2 font-semibold">Email</label>
                <input
                  type="email"
                  value={contactForm.email}
                  onChange={(e) => setContactForm({...contactForm, email: e.target.value})}
                  className={`w-full p-3 rounded-xl ${isDarkMode ? 'bg-white/10 border-cyan-500/30 text-white' : 'bg-white border-purple-300 text-gray-900'} border outline-none focus:border-cyan-400 transition-colors`}
                  placeholder="your@email.com"
                />
              </div>
              
              <div>
                <label className="block mb-2 font-semibold">Message</label>
                <textarea
                  value={contactForm.message}
                  onChange={(e) => setContactForm({...contactForm, message: e.target.value})}
                  rows="4"
                  className={`w-full p-3 rounded-xl ${isDarkMode ? 'bg-white/10 border-cyan-500/30 text-white' : 'bg-white border-purple-300 text-gray-900'} border outline-none focus:border-cyan-400 transition-colors resize-none`}
                  placeholder="Your message..."
                />
              </div>

              <button
                onClick={handleContact}
                className={`w-full py-3 px-6 rounded-xl font-bold transition-all hover:scale-105 ${
                  isDarkMode 
                    ? 'bg-gradient-to-r from-cyan-500 to-purple-600 hover:from-cyan-400 hover:to-purple-500' 
                    : 'bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-400 hover:to-pink-400'
                } text-white shadow-lg flex items-center justify-center gap-2`}
              >
                <Send className="w-5 h-5" /> Send Message
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Feedback Modal */}
      {showFeedbackModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/70 backdrop-blur-md">
          <div className={`${cardBg} border ${isDarkMode ? 'border-cyan-500/50' : 'border-purple-400'} rounded-3xl p-8 max-w-md w-full relative shadow-2xl`}>
            <button 
              onClick={() => setShowFeedbackModal(false)}
              className="absolute top-4 right-4 p-2 hover:bg-red-500/20 rounded-full transition-colors group"
            >
              <X className="w-6 h-6 group-hover:text-red-400" />
            </button>
            
            <div className="text-center mb-6">
              <div className={`w-16 h-16 mx-auto mb-4 rounded-full bg-gradient-to-br from-yellow-500 to-orange-500 flex items-center justify-center`}>
                <MessageCircle className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-2xl font-bold mb-2 bg-gradient-to-r from-cyan-300 to-purple-400 bg-clip-text text-transparent">
                Share Your Feedback
              </h3>
              <p className="opacity-75">Help us improve your experience!</p>
            </div>

            <div className="space-y-4">
              <div>
                <label className="block mb-2 font-semibold">Rating</label>
                <div className="flex justify-center gap-2">
                  {[1, 2, 3, 4, 5].map((star) => (
                    <button
                      key={star}
                      onClick={() => setFeedbackForm({...feedbackForm, rating: star})}
                      className="transition-transform hover:scale-125"
                    >
                      <Star 
                        className={`w-8 h-8 ${star <= feedbackForm.rating ? 'fill-yellow-400 text-yellow-400' : 'text-gray-400'}`}
                      />
                    </button>
                  ))}
                </div>
                <p className="text-center mt-2 text-sm opacity-75">{feedbackForm.rating} out of 5 stars</p>
              </div>
              
              <div>
                <label className="block mb-2 font-semibold">Your Feedback</label>
                <textarea
                  value={feedbackForm.message}
                  onChange={(e) => setFeedbackForm({...feedbackForm, message: e.target.value})}
                  rows="4"
                  className={`w-full p-3 rounded-xl ${isDarkMode ? 'bg-white/10 border-cyan-500/30 text-white' : 'bg-white border-purple-300 text-gray-900'} border outline-none focus:border-cyan-400 transition-colors resize-none`}
                  placeholder="Tell us what you think..."
                />
              </div>

              <button
                onClick={handleFeedback}
                className={`w-full py-3 px-6 rounded-xl font-bold transition-all hover:scale-105 ${
                  isDarkMode 
                    ? 'bg-gradient-to-r from-yellow-500 to-orange-600 hover:from-yellow-400 hover:to-orange-500' 
                    : 'bg-gradient-to-r from-yellow-600 to-orange-600 hover:from-yellow-500 hover:to-orange-500'
                } text-white shadow-lg flex items-center justify-center gap-2`}
              >
                <Send className="w-5 h-5" /> Submit Feedback
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Wonder Detail Modal */}
      {selectedWonder && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-md overflow-y-auto">
          <div className={`${cardBg} border-2 ${isDarkMode ? 'border-cyan-500/50' : 'border-purple-400'} rounded-3xl p-6 sm:p-8 max-w-2xl w-full my-8 relative shadow-2xl`}>
            <button 
              onClick={() => setSelectedWonder(null)}
              className="absolute top-4 right-4 p-3 hover:bg-red-500/20 rounded-full transition-all z-10 group"
            >
              <X className="w-6 h-6 group-hover:text-red-400 group-hover:scale-110 transition-all" strokeWidth={2.5} />
            </button>
            
            <div className={`w-24 h-24 rounded-2xl bg-gradient-to-br ${selectedWonder.color} flex items-center justify-center mb-6 mx-auto shadow-lg`}
                 style={{ animation: 'float 3s infinite' }}>
              <selectedWonder.icon className="w-14 h-14 text-white" strokeWidth={2} />
            </div>
            
            <h3 className="text-3xl sm:text-4xl font-bold mb-4 text-center bg-gradient-to-r from-cyan-300 to-purple-400 bg-clip-text text-transparent">
              {selectedWonder.title}
            </h3>
            
            <p className="text-base sm:text-lg mb-6 opacity-90 leading-relaxed text-center">
              {selectedWonder.fullDesc}
            </p>
            
            <div className={`${isDarkMode ? 'bg-cyan-500/10 border border-cyan-400/30' : 'bg-purple-100 border border-purple-300'} rounded-xl p-4 mb-6`}>
              <div className="grid sm:grid-cols-2 gap-4 text-sm font-semibold">
                <div className="flex items-center gap-2">
                  <Calendar className="w-5 h-5 text-cyan-400" />
                  <span>Duration: {selectedWonder.duration}</span>
                </div>
                <div className="flex items-center gap-2">
                  <Star className="w-5 h-5 text-yellow-400" />
                  <span>Level: {selectedWonder.difficulty}</span>
                </div>
              </div>
            </div>
            
            <h4 className="text-xl font-bold mb-4 flex items-center gap-2">
              <Sparkles className={accentColor} />
              What You'll Experience:
            </h4>
            <ul className="space-y-3 mb-6">
              {selectedWonder.features.map((feature, idx) => (
                <li key={idx} className="flex items-start gap-3 opacity-90 hover:opacity-100 transition-opacity">
                  <span className="text-xl">{feature}</span>
                </li>
              ))}
            </ul>
            
            <div className="flex flex-col sm:flex-row gap-3">
              <button 
                onClick={() => {
                  setSelectedWonder(null);
                  scrollToSection(packagesRef);
                }}
                className={`flex-1 py-4 px-6 rounded-xl font-bold transition-all hover:scale-105 ${
                  isDarkMode 
                    ? 'bg-gradient-to-r from-cyan-500 to-purple-600 hover:from-cyan-400 hover:to-purple-500' 
                    : 'bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-400 hover:to-pink-400'
                } text-white shadow-lg`}
              >
                Book This Experience 🚀
              </button>
              <button 
                onClick={() => setSelectedWonder(null)}
                className={`sm:w-auto px-6 py-4 rounded-xl font-semibold border-2 transition-all hover:scale-105 ${
                  isDarkMode 
                    ? 'border-cyan-400 hover:bg-cyan-400/10' 
                    : 'border-purple-500 hover:bg-purple-500/10'
                }`}
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Sidebar - Left Side (Toggle) */}
      <div className={`fixed top-0 left-0 h-full w-64 ${cardBg} border-r ${isDarkMode ? 'border-cyan-500/30' : 'border-purple-300'} z-[60] shadow-2xl overflow-y-auto transform transition-transform duration-300 ${showSidebar ? 'translate-x-0' : '-translate-x-full'}`}>
        <div className="p-6">
          {/* Close Button */}
          <button 
            onClick={() => setShowSidebar(false)}
            className="absolute top-4 right-4 p-2 hover:bg-white/10 rounded-full transition-colors"
          >
            <X className="w-5 h-5" />
          </button>

          {/* Logo */}
          <div className="flex items-center gap-3 mb-8 mt-2">
            <Sparkles className={`${accentColor} w-10 h-10`} />
            <div>
              <h2 className="text-xl font-bold bg-gradient-to-r from-cyan-400 to-purple-500 bg-clip-text text-transparent">
                Aetheria
              </h2>
              <p className="text-xs opacity-75">Voyages</p>
            </div>
          </div>

          {/* Navigation Links */}
          <div className="space-y-2 mb-6">
            <button 
              onClick={(e) => {
                e.stopPropagation();
                window.scrollTo({ top: 0, behavior: 'smooth' });
                setShowSidebar(false);
              }}
              className={`w-full p-3 rounded-lg transition-all text-left flex items-center gap-3 font-semibold ${
                isDarkMode 
                  ? 'hover:bg-cyan-500/20 hover:text-cyan-400' 
                  : 'hover:bg-purple-500/20 hover:text-purple-600'
              }`}
            >
              <Home className="w-5 h-5" /> Home
            </button>
            <button 
              onClick={(e) => {
                e.stopPropagation();
                scrollToSection(featuresRef);
                setShowSidebar(false);
              }}
              className={`w-full p-3 rounded-lg transition-all text-left flex items-center gap-3 ${
                isDarkMode 
                  ? 'hover:bg-cyan-500/20 hover:text-cyan-400' 
                  : 'hover:bg-purple-500/20 hover:text-purple-600'
              }`}
            >
              <MapPin className="w-5 h-5" /> Wonders
            </button>
            <button 
              onClick={(e) => {
                e.stopPropagation();
                scrollToSection(packagesRef);
                setShowSidebar(false);
              }}
              className={`w-full p-3 rounded-lg transition-all text-left flex items-center gap-3 ${
                isDarkMode 
                  ? 'hover:bg-cyan-500/20 hover:text-cyan-400' 
                  : 'hover:bg-purple-500/20 hover:text-purple-600'
              }`}
            >
              <Package className="w-5 h-5" /> Packages
            </button>
            <button 
              onClick={(e) => {
                e.stopPropagation();
                scrollToSection(journeyRef);
                setShowSidebar(false);
              }}
              className={`w-full p-3 rounded-lg transition-all text-left flex items-center gap-3 ${
                isDarkMode 
                  ? 'hover:bg-cyan-500/20 hover:text-cyan-400' 
                  : 'hover:bg-purple-500/20 hover:text-purple-600'
              }`}
            >
              <Rocket className="w-5 h-5" /> Journey
            </button>
          </div>
          
          <div className="border-t border-white/10 my-4"></div>

          {/* Contact & Feedback */}
          <div className="space-y-2 mb-6">
            <button 
              onClick={(e) => {
                e.stopPropagation();
                setShowContactModal(true);
                setShowSidebar(false);
              }}
              className={`w-full p-3 rounded-lg transition-all text-left flex items-center gap-3 ${
                isDarkMode 
                  ? 'hover:bg-cyan-500/20 hover:text-cyan-400' 
                  : 'hover:bg-purple-500/20 hover:text-purple-600'
              }`}
            >
              <Mail className="w-5 h-5" /> Contact
            </button>
            <button 
              onClick={(e) => {
                e.stopPropagation();
                setShowFeedbackModal(true);
                setShowSidebar(false);
              }}
              className={`w-full p-3 rounded-lg transition-all text-left flex items-center gap-3 ${
                isDarkMode 
                  ? 'hover:bg-cyan-500/20 hover:text-cyan-400' 
                  : 'hover:bg-purple-500/20 hover:text-purple-600'
              }`}
            >
              <MessageCircle className="w-5 h-5" /> Feedback
            </button>
          </div>

          <div className="border-t border-white/10 my-4"></div>

          {/* Appearance Settings */}
          <div className="space-y-2">
            <p className="text-xs font-semibold opacity-50 mb-2 px-3">APPEARANCE</p>
            <div className="flex gap-2">
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  setIsDarkMode(true);
                }}
                className={`flex-1 py-2 px-3 rounded-lg font-semibold transition-all flex items-center justify-center gap-2 ${
                  isDarkMode 
                    ? 'bg-gradient-to-r from-cyan-500 to-purple-600 text-white' 
                    : 'bg-white/10 hover:bg-white/20'
                }`}
              >
                <Moon className="w-4 h-4" />
              </button>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  setIsDarkMode(false);
                }}
                className={`flex-1 py-2 px-3 rounded-lg font-semibold transition-all flex items-center justify-center gap-2 ${
                  !isDarkMode 
                    ? 'bg-gradient-to-r from-purple-500 to-pink-500 text-white' 
                    : 'bg-white/10 hover:bg-white/20'
                }`}
              >
                <Sun className="w-4 h-4" />
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Overlay when sidebar is open */}
      {showSidebar && (
        <div 
          className="fixed inset-0 bg-black/50 z-[55]"
          onClick={() => setShowSidebar(false)}
        />
      )}

      {/* Edit Profile Modal */}
      {showEditProfile && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/70 backdrop-blur-md">
          <div className={`${cardBg} border ${isDarkMode ? 'border-cyan-500/50' : 'border-purple-400'} rounded-3xl p-8 max-w-md w-full relative shadow-2xl`}>
            <button 
              onClick={() => setShowEditProfile(false)}
              className="absolute top-4 right-4 p-2 hover:bg-red-500/20 rounded-full transition-colors group"
            >
              <X className="w-6 h-6 group-hover:text-red-400" />
            </button>
            
            <div className="text-center mb-6">
              <div className={`w-16 h-16 mx-auto mb-4 rounded-full bg-gradient-to-br from-cyan-500 to-purple-600 flex items-center justify-center`}>
                <User className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-2xl font-bold mb-2 bg-gradient-to-r from-cyan-300 to-purple-400 bg-clip-text text-transparent">
                Edit Profile
              </h3>
            </div>

            <div className="space-y-4">
              <div>
                <label className="block mb-2 font-semibold">Name</label>
                <input
                  type="text"
                  value={editForm.name}
                  onChange={(e) => setEditForm({...editForm, name: e.target.value})}
                  className={`w-full p-3 rounded-xl ${isDarkMode ? 'bg-white/10 border-cyan-500/30 text-white' : 'bg-white border-purple-300 text-gray-900'} border outline-none focus:border-cyan-400 transition-colors`}
                  placeholder="Your name"
                />
              </div>
              
              <div>
                <label className="block mb-2 font-semibold">Email</label>
                <input
                  type="email"
                  value={editForm.email}
                  onChange={(e) => setEditForm({...editForm, email: e.target.value})}
                  className={`w-full p-3 rounded-xl ${isDarkMode ? 'bg-white/10 border-cyan-500/30 text-white' : 'bg-white border-purple-300 text-gray-900'} border outline-none focus:border-cyan-400 transition-colors`}
                  placeholder="your@email.com"
                />
              </div>

              <button
                onClick={handleSaveProfile}
                className={`w-full py-3 px-6 rounded-xl font-bold transition-all hover:scale-105 ${
                  isDarkMode 
                    ? 'bg-gradient-to-r from-cyan-500 to-purple-600 hover:from-cyan-400 hover:to-purple-500' 
                    : 'bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-400 hover:to-pink-400'
                } text-white shadow-lg`}
              >
                Save Changes ✅
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Animated Stars Background */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        {[...Array(50)].map((_, i) => (
          <div
            key={i}
            className={`absolute rounded-full ${isDarkMode ? 'bg-white' : 'bg-purple-400'}`}
            style={{
              width: Math.random() * 3 + 1 + 'px',
              height: Math.random() * 3 + 1 + 'px',
              left: Math.random() * 100 + '%',
              top: Math.random() * 100 + '%',
              animation: `twinkle ${Math.random() * 3 + 2}s infinite`,
              opacity: Math.random() * 0.7 + 0.3
            }}
          />
        ))}
      </div>

      <style>{`
        @keyframes twinkle {
          0%, 100% { opacity: 0.3; }
          50% { opacity: 1; }
        }
        @keyframes float {
          0%, 100% { transform: translateY(0px); }
          50% { transform: translateY(-20px); }
        }
        @keyframes glow {
          0%, 100% { box-shadow: 0 0 20px rgba(34, 211, 238, 0.5); }
          50% { box-shadow: 0 0 40px rgba(34, 211, 238, 0.8); }
        }
        @keyframes pulse {
          0%, 100% { transform: scale(1); }
          50% { transform: scale(1.05); }
        }
      `}</style>

      <div className="relative z-10">
        {/* Fixed Navigation Bar */}
        <nav className={`sticky top-0 z-40 ${cardBg} border-b ${isDarkMode ? 'border-cyan-500/30' : 'border-purple-300'} backdrop-blur-xl`}>
          <div className="px-4 sm:px-6">
            <div className="flex justify-between items-center h-16">
              {/* Left side - Menu + Logo */}
              <div className="flex items-center gap-3">
                <button
                  onClick={() => setShowSidebar(true)}
                  className={`p-2 rounded-lg transition-all hover:scale-105 ${
                    isDarkMode 
                      ? 'hover:bg-cyan-500/20' 
                      : 'hover:bg-purple-500/20'
                  }`}
                >
                  <Menu className={`w-5 h-5 ${accentColor}`} />
                </button>
                <Sparkles className={`${accentColor} w-6 h-6`} />
                <span className="text-lg font-bold bg-gradient-to-r from-cyan-400 to-purple-500 bg-clip-text text-transparent">
                  Aetheria Voyages
                </span>
              </div>

              {/* Right side - Navigation + Auth */}
              <div className="flex items-center gap-8">
                {/* Navigation Links */}
                <div className="hidden md:flex items-center gap-8">
                  <button
                    onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
                    className="hover:text-cyan-400 transition-colors font-medium px-2 py-1"
                  >
                    Home
                  </button>
                  <button
                    onClick={() => scrollToSection(featuresRef)}
                    className="hover:text-cyan-400 transition-colors font-medium px-2 py-1"
                  >
                    Wonders
                  </button>
                  <button
                    onClick={() => scrollToSection(journeyRef)}
                    className="hover:text-cyan-400 transition-colors font-medium px-2 py-1"
                  >
                    Journey
                  </button>
                  <button
                    onClick={() => scrollToSection(packagesRef)}
                    className="hover:text-cyan-400 transition-colors font-medium px-2 py-1"
                  >
                    Packages
                  </button>
                </div>

                {/* Auth Buttons */}
                {!isLoggedIn ? (
                  <div className="flex items-center gap-3">
                    <button
                      onClick={() => {
                        setAuthMode('login');
                        setShowAuthModal(true);
                      }}
                      className="flex items-center gap-2 py-2 px-4 rounded-lg hover:bg-white/10 transition-colors font-semibold"
                    >
                      <LogIn className="w-4 h-4" /> Login
                    </button>
                    <button
                      onClick={() => {
                        setAuthMode('signup');
                        setShowAuthModal(true);
                      }}
                      className={`flex items-center gap-2 py-2 px-6 rounded-lg ${
                        isDarkMode 
                          ? 'bg-gradient-to-r from-cyan-500 to-purple-600 hover:from-cyan-400 hover:to-purple-500' 
                          : 'bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-400 hover:to-pink-400'
                      } text-white transition-all font-semibold`}
                    >
                      <UserPlus className="w-4 h-4" /> Sign Up
                    </button>
                  </div>
                ) : (
                  <div className="relative">
                    <button
                      onClick={() => setShowProfileDropdown(!showProfileDropdown)}
                      className="flex items-center gap-3 py-2 px-4 rounded-lg bg-white/10 hover:bg-white/20 transition-colors"
                    >
                      <div className="w-8 h-8 rounded-full bg-gradient-to-br from-cyan-500 to-purple-600 flex items-center justify-center">
                        <User className="w-5 h-5 text-white" />
                      </div>
                      <span className="font-semibold hidden sm:inline">{userInfo?.name}</span>
                      <ChevronRight className={`w-4 h-4 transition-transform ${showProfileDropdown ? 'rotate-90' : ''}`} />
                    </button>

                    {showProfileDropdown && (
                      <div className={`absolute right-0 mt-2 w-64 ${cardBg} border ${isDarkMode ? 'border-cyan-500/30' : 'border-purple-300'} rounded-xl shadow-2xl overflow-hidden`}>
                        <div className="p-4 border-b border-white/10">
                          <p className="font-bold text-lg">{userInfo?.name}</p>
                          <p className="text-sm opacity-75">{userInfo?.email}</p>
                        </div>
                        
                        <div className="p-2">
                          <button
                            onClick={handleEditProfile}
                            className="w-full p-3 rounded-lg hover:bg-white/10 transition-colors text-left flex items-center gap-3"
                          >
                            <User className="w-5 h-5 text-blue-400" />
                            <span>Edit Profile</span>
                          </button>
                          <button
                            onClick={handleDeleteAccount}
                            className="w-full p-3 rounded-lg hover:bg-red-500/20 transition-colors text-left flex items-center gap-3 text-red-400"
                          >
                            <X className="w-5 h-5" />
                            <span>Delete Account</span>
                          </button>
                          <div className="border-t border-white/10 my-2"></div>
                          <button
                            onClick={handleLogout}
                            className="w-full p-3 rounded-lg hover:bg-white/10 transition-colors text-left flex items-center gap-3"
                          >
                            <LogOut className="w-5 h-5 text-orange-400" />
                            <span>Logout</span>
                          </button>
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            </div>
          </div>
        </nav>

        <div className="max-w-7xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
          {/* Hero Section */}
          <div className={`${cardBg} border ${isDarkMode ? 'border-cyan-500/30' : 'border-purple-300'} rounded-3xl p-8 sm:p-12 mb-12 text-center relative overflow-hidden`}
               style={{ animation: 'glow 3s infinite' }}>
            <div className="absolute top-0 right-0 w-64 h-64 bg-gradient-to-br from-cyan-500/20 to-purple-500/20 rounded-full blur-3xl" />
            <div className="relative z-10">
              <Globe className={`${accentColor} w-20 h-20 mx-auto mb-6`} style={{ animation: 'float 3s infinite' }} />
              <h2 className="text-4xl sm:text-6xl font-bold mb-4 bg-gradient-to-r from-cyan-300 to-purple-400 bg-clip-text text-transparent">
                Welcome to Aetheria
              </h2>
              <p className="text-xl sm:text-2xl mb-6 opacity-90">
                The Crystal Planet of Eternal Twilight
              </p>
              <p className="text-lg max-w-3xl mx-auto opacity-80 leading-relaxed mb-8">
                Discover a world where twin suns paint endless purple skies, crystalline mountains sing in the wind, 
                and bioluminescent oceans glow beneath floating islands. Aetheria awaits your arrival.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <button 
                  onClick={() => scrollToSection(packagesRef)}
                  className={`py-4 px-8 rounded-xl font-bold text-lg transition-all transform hover:scale-105 ${
                    isDarkMode 
                      ? 'bg-gradient-to-r from-cyan-500 to-purple-600 hover:from-cyan-400 hover:to-purple-500' 
                      : 'bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500'
                  } text-white shadow-lg hover:shadow-2xl`}
                  style={{ animation: 'pulse 2s infinite' }}
                >
                  Explore Packages
                </button>
                <button 
                  onClick={() => scrollToSection(featuresRef)}
                  className={`py-4 px-8 rounded-xl font-bold text-lg border-2 transition-all transform hover:scale-105 ${
                    isDarkMode 
                      ? 'border-cyan-400 hover:bg-cyan-400/10' 
                      : 'border-purple-500 hover:bg-purple-500/10'
                  }`}
                >
                  Discover Wonders
                </button>
              </div>
            </div>
          </div>

          {/* Planet Features */}
          <div ref={featuresRef} className="mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold mb-4 text-center bg-gradient-to-r from-cyan-300 to-purple-400 bg-clip-text text-transparent">
              Discover Aetheria's Wonders
            </h2>
            <p className="text-center opacity-75 mb-8 text-lg">Click to explore each wonder in detail! 👇</p>
            <div className="grid md:grid-cols-3 gap-6">
              {wonders.map((wonder) => (
                <div 
                  key={wonder.id} 
                  onClick={() => setSelectedWonder(wonder)}
                  className={`${cardBg} border ${isDarkMode ? 'border-purple-500/30' : 'border-purple-300'} rounded-2xl p-6 hover:scale-105 transition-all cursor-pointer group`}
                >
                  <div className={`w-16 h-16 rounded-xl bg-gradient-to-br ${wonder.color} flex items-center justify-center mb-4 group-hover:scale-110 group-hover:rotate-6 transition-transform`}>
                    <wonder.icon className="w-8 h-8 text-white" />
                  </div>
                  <h3 className="text-xl font-bold mb-2 group-hover:text-cyan-400 transition-colors">{wonder.title}</h3>
                  <p className="opacity-75 mb-4">{wonder.desc}</p>
                  <div className={`text-sm font-semibold ${accentColor} flex items-center gap-2 group-hover:gap-4 transition-all`}>
                    Click to Explore <ChevronRight className="w-4 h-4" />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Why Choose Us */}
          <div className={`${cardBg} border ${isDarkMode ? 'border-cyan-500/30' : 'border-purple-300'} rounded-3xl p-8 mb-12`}>
            <h2 className="text-3xl font-bold mb-8 text-center bg-gradient-to-r from-cyan-300 to-purple-400 bg-clip-text text-transparent">
              Why Travel with Us?
            </h2>
            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
              {[
                { icon: Shield, title: "100% Safety", desc: "Advanced life support systems", color: "from-green-500 to-emerald-500" },
                { icon: Rocket, title: "FTL Travel", desc: "Reach Aetheria in just 6 hours", color: "from-cyan-500 to-blue-500" },
                { icon: Users, title: "Expert Guides", desc: "Native Aetherian companions", color: "from-purple-500 to-pink-500" },
                { icon: Star, title: "Premium Experience", desc: "5-star cosmic hospitality", color: "from-yellow-500 to-orange-500" }
              ].map((item, idx) => (
                <div key={idx} className="text-center group hover:scale-105 transition-transform">
                  <div className={`w-16 h-16 rounded-full bg-gradient-to-br ${item.color} flex items-center justify-center mx-auto mb-3 group-hover:rotate-12 transition-transform`}>
                    <item.icon className="w-8 h-8 text-white" />
                  </div>
                  <h4 className="font-semibold mb-1">{item.title}</h4>
                  <p className="text-sm opacity-75">{item.desc}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Travel Packages */}
          <div ref={packagesRef} className={`${cardBg} border ${isDarkMode ? 'border-purple-500/30' : 'border-purple-300'} rounded-3xl p-8 mb-12`}>
            <h2 className="text-3xl sm:text-4xl font-bold mb-8 text-center bg-gradient-to-r from-cyan-300 to-purple-400 bg-clip-text text-transparent">
              Choose Your Adventure
            </h2>
            <div className="grid md:grid-cols-3 gap-6">
              {packages.map((pkg) => (
                <div
                  key={pkg.id}
                  className={`${cardBg} border-2 rounded-2xl p-6 transition-all hover:scale-105 relative ${
                    pkg.popular ? (isDarkMode ? 'border-cyan-400' : 'border-purple-500') : (isDarkMode ? 'border-purple-500/30' : 'border-purple-300')
                  }`}
                >
                  {pkg.popular && (
                    <div className={`absolute -top-3 left-1/2 -translate-x-1/2 px-4 py-1 rounded-full text-sm font-bold ${
                      isDarkMode ? 'bg-gradient-to-r from-cyan-500 to-purple-600' : 'bg-gradient-to-r from-purple-500 to-pink-500'
                    } text-white`}>
                      MOST POPULAR ⭐
                    </div>
                  )}
                  <h3 className="text-2xl font-bold mb-2">{pkg.name}</h3>
                  <div className="flex items-baseline gap-2 mb-4">
                    <span className={`text-3xl font-bold ${accentColor}`}>{pkg.price}</span>
                    <span className="opacity-75 text-sm">per person</span>
                  </div>
                  <div className="flex items-center gap-2 mb-6 opacity-75">
                    <Calendar className="w-4 h-4" />
                    <span>{pkg.duration}</span>
                  </div>
                  <ul className="space-y-2 mb-6">
                    {pkg.features.map((feature, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <ChevronRight className={`${accentColor} w-5 h-5 flex-shrink-0 mt-0.5`} />
                        <span className="opacity-90 text-sm">{feature}</span>
                      </li>
                    ))}
                  </ul>
                  <button 
                    onClick={() => handleBooking(pkg)}
                    className={`w-full py-3 px-6 rounded-xl font-semibold transition-all hover:scale-105 ${
                      isDarkMode 
                        ? 'bg-gradient-to-r from-cyan-500 to-purple-600 hover:from-cyan-400 hover:to-purple-500' 
                        : 'bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-400 hover:to-pink-400'
                    } text-white shadow-lg hover:shadow-xl`}
                  >
                    Book This Package
                  </button>
                </div>
              ))}
            </div>
          </div>

          {/* Journey Timeline */}
          <div ref={journeyRef} className={`${cardBg} border ${isDarkMode ? 'border-cyan-500/30' : 'border-purple-300'} rounded-3xl p-8 mb-12`}>
            <h2 className="text-3xl sm:text-4xl font-bold mb-8 text-center bg-gradient-to-r from-cyan-300 to-purple-400 bg-clip-text text-transparent">
              Your Journey Timeline
            </h2>
            <div className="space-y-6">
              {[
                { step: "01", title: "Departure from Earth", desc: "Launch from our lunar station", icon: Rocket },
                { step: "02", title: "FTL Jump", desc: "Experience faster-than-light travel", icon: Sparkles },
                { step: "03", title: "Orbital Approach", desc: "First view of Aetheria's purple skies", icon: Globe },
                { step: "04", title: "Surface Landing", desc: "Touch down at Crystal Bay Spaceport", icon: Star },
                { step: "05", title: "Welcome Ceremony", desc: "Meet your Aetherian guide", icon: Users }
              ].map((item, idx) => (
                <div key={idx} className="flex gap-6 items-start group hover:translate-x-2 transition-all">
                  <div className={`${accentColor} text-2xl font-bold w-16 flex-shrink-0 flex items-center gap-2`}>
                    <span>{item.step}</span>
                  </div>
                  <div className={`w-12 h-12 rounded-full bg-gradient-to-br from-cyan-500 to-purple-600 flex items-center justify-center flex-shrink-0 group-hover:scale-110 transition-transform`}>
                    <item.icon className="w-6 h-6 text-white" />
                  </div>
                  <div className="flex-1">
                    <h4 className="text-xl font-semibold mb-1 group-hover:text-cyan-400 transition-colors">{item.title}</h4>
                    <p className="opacity-75">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Booking Form */}
          {showBooking && (
            <div ref={bookingRef} className={`${cardBg} border ${isDarkMode ? 'border-cyan-500/30' : 'border-purple-300'} rounded-3xl p-8 mb-12`}>
              <h2 className="text-3xl font-bold mb-6 text-center bg-gradient-to-r from-cyan-300 to-purple-400 bg-clip-text text-transparent">
                Complete Your Booking
              </h2>
              <div className={`${isDarkMode ? 'bg-cyan-500/10' : 'bg-purple-100'} rounded-xl p-4 mb-6`}>
                <p className="font-semibold mb-1">Selected Package: {selectedPackage.name}</p>
                <p className="opacity-75">Price: {selectedPackage.price} | Duration: {selectedPackage.duration}</p>
              </div>
              <div className="space-y-4">
                <div>
                  <label className="block mb-2 font-semibold">Full Name</label>
                  <input
                    type="text"
                    value={formData.name}
                    onChange={(e) => setFormData({...formData, name: e.target.value})}
                    className={`w-full p-3 rounded-xl ${isDarkMode ? 'bg-white/10 border-cyan-500/30 text-white' : 'bg-white border-purple-300 text-gray-900'} border outline-none focus:border-cyan-400 transition-colors`}
                    placeholder="Enter your full name"
                  />
                </div>
                <div>
                  <label className="block mb-2 font-semibold">Email Address</label>
                  <input
                    type="email"
                    value={formData.email}
                    onChange={(e) => setFormData({...formData, email: e.target.value})}
                    className={`w-full p-3 rounded-xl ${isDarkMode ? 'bg-white/10 border-cyan-500/30 text-white' : 'bg-white border-purple-300 text-gray-900'} border outline-none focus:border-cyan-400 transition-colors`}
                    placeholder="your@email.com"
                  />
                </div>
                <div>
                  <label className="block mb-2 font-semibold">Phone Number</label>
                  <input
                    type="tel"
                    value={formData.phone}
                    onChange={(e) => setFormData({...formData, phone: e.target.value})}
                    className={`w-full p-3 rounded-xl ${isDarkMode ? 'bg-white/10 border-cyan-500/30 text-white' : 'bg-white border-purple-300 text-gray-900'} border outline-none focus:border-cyan-400 transition-colors`}
                    placeholder="+1 234 567 8900"
                  />
                </div>
                <button
                  onClick={(e) => {
                    e.preventDefault();
                    if (formData.name && formData.email && formData.phone) {
                      handleSubmit(e);
                    } else {
                      showNotification('Please fill all fields! 📝', 'error');
                    }
                  }}
                  className={`w-full py-4 px-8 rounded-xl font-bold text-lg transition-all transform hover:scale-105 ${
                    isDarkMode 
                      ? 'bg-gradient-to-r from-cyan-500 to-purple-600 hover:from-cyan-400 hover:to-purple-500' 
                      : 'bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500'
                  } text-white shadow-lg hover:shadow-2xl`}
                >
                  Confirm Booking 🚀
                </button>
              </div>
            </div>
          )}

          {/* Contact/CTA Section */}
          <div className={`${cardBg} border ${isDarkMode ? 'border-purple-500/30' : 'border-purple-300'} rounded-3xl p-12 text-center relative overflow-hidden mb-12`}>
            <div className="absolute inset-0 bg-gradient-to-r from-cyan-500/10 to-purple-500/10" />
            <div className="relative z-10">
              <h2 className="text-4xl font-bold mb-4 bg-gradient-to-r from-cyan-300 to-purple-400 bg-clip-text text-transparent">
                Questions? We're Here to Help!
              </h2>
              <p className="text-lg mb-6 opacity-90">
                Our space travel experts are available 24/7 to answer your questions
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center items-center mb-6">
                <div className="flex items-center gap-2">
                  <Mail className={accentColor} />
                  <span>voyages@aetheria.space</span>
                </div>
                <div className="flex items-center gap-2">
                  <Phone className={accentColor} />
                  <span>+1-SPACE-2025</span>
                </div>
              </div>
              <button 
                onClick={() => setShowContactModal(true)}
                className={`py-3 px-8 rounded-xl font-bold transition-all hover:scale-105 ${
                  isDarkMode 
                    ? 'bg-gradient-to-r from-cyan-500 to-purple-600 hover:from-cyan-400 hover:to-purple-500' 
                    : 'bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500'
                } text-white shadow-lg`}
              >
                Contact Us Now
              </button>
            </div>
          </div>

          {/* Footer */}
          <div className="text-center py-8 opacity-75 border-t border-cyan-500/20">
            <p className="mb-2">© 2025 Aetheria Voyages | Making Dreams Reality, One Planet at a Time</p>
            <p className="text-sm">Built for Weekend Build Marathon - Discover Your Own Planet 🚀</p>
          </div>
        </div>
      </div>
    </div>
  );
}